spring.application.name=golf
jwt.secret=your-very-long-secret-key-at-least-256-bits-long
jwt.expiration=86400000
server.port=8080



spring.datasource.url=${DB_URL:jdbc:postgresql://db.vvokthxdofmdnjdtzyga.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:SupaBase1234S}
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://postgres:SupaBase1234S@db.vvokthxdofmdnjdtzyga.supabase.co:5432/postgres
#spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000





stripe.secret-key=sk_test_51TlEwpRz48Ds9kA5Lkcy0286wHwpjxtGjAXiZ81LSJfToPFgjCvdQgZW4GYfvzWMyUZyIcByuLRf7Lw1ERHCKvCG00trFqv2sR
stripe.public-key=pk_test_51TlEwpRz48Ds9kA5fAvE9d6CqG8uVhAHItbaYcNgFNeUSCZBk6SawcqQgO9ldCJqaVyndAJpVZfpz2y72dyioTYV00jS24piND
stripe.api.key=sk_test_51TlEwpRz48Ds9kA5Lkcy0286wHwpjxtGjAXiZ81LSJfToPFgjCvdQgZW4GYfvzWMyUZyIcByuLRf7Lw1ERHCKvCG00trFqv2sR

#stripe.api.key=sk_test_51TlEwpRz48Ds9kA5Lkcy0286wHwpjxtGjAXiZ81LSJfToPFgjCvdQgZW4GYfvzWMyUZyIcByuLRf7Lw1ERHCKvCG00trFqv2sR
stripe.webhook.secret=whsec_u2cgkPA6YGRgMWPDfLjCp6xvb6PXh4YD


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your@email.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB



stripe.price.monthly=price_your_monthly_price_id
stripe.price.yearly=price_your_yearly_price_id
stripe.price.monthly.amount=9.99
stripe.price.yearly.amount=99.99


spring.web.cors.allowed-origins=http://localhost:4000,http://localhost:5173,https://golf-charity-subscription-platform-frontend-luc1kwj2f.vercel.app
spring.web.cors.allowed-headers=*
#spring.web.cors.allowed-headers=Authorization,Content-Type,Accept,Origin,X-Requested-With
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600



